// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4hrCF1qXVSVCMPWG-OixkdQn15L8SUws',
    appId: '1:460186405285:web:c7fa72b0ded247b2a6c04c',
    messagingSenderId: '460186405285',
    projectId: 'tutorialapp-6ca7a',
    authDomain: 'tutorialapp-6ca7a.firebaseapp.com',
    storageBucket: 'tutorialapp-6ca7a.appspot.com',
    measurementId: 'G-NL1NH2DTTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Hy7Y37gi-0gY-1u7O1RSxKpkdl76TUA',
    appId: '1:460186405285:android:073a0a69659ab771a6c04c',
    messagingSenderId: '460186405285',
    projectId: 'tutorialapp-6ca7a',
    storageBucket: 'tutorialapp-6ca7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYX896bl9n48s7WsLlyWy5NN5Nd35X_AU',
    appId: '1:460186405285:ios:006009846301b6f2a6c04c',
    messagingSenderId: '460186405285',
    projectId: 'tutorialapp-6ca7a',
    storageBucket: 'tutorialapp-6ca7a.appspot.com',
    iosBundleId: 'com.example.tutorialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYX896bl9n48s7WsLlyWy5NN5Nd35X_AU',
    appId: '1:460186405285:ios:41372fca7a1b2d99a6c04c',
    messagingSenderId: '460186405285',
    projectId: 'tutorialapp-6ca7a',
    storageBucket: 'tutorialapp-6ca7a.appspot.com',
    iosBundleId: 'com.example.tutorialapp.RunnerTests',
  );
}
